[package]
name = "deckard"
version = "0.1.0"
authors = ["Gregory Smith <gasmith@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.13.0"
rand = "0.8.5"
